print("-----------------------------------")
print("Tugas 1 Sistem Operasi Kelas B")
print("-----------------------------------")
print("Nama : Zulfa Febi Afidria")
print("NPM : 21083010096")
print("Notes:")
print("-----------------------------------")
print("Hello Dunia!")
print("ini adalah skrip bash pertamaku di Linux")
